version: 2

sources:
  - name: movielens_raw
    database: SF_DBT_DEMO
    schema: SCHEMA_DEMO
    tables:
      - name: movies
      - name: ratings
      - name: tags
      - name: links
      - name: genome_scores
      - name: genome_tags